#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> A){
    map<int, int> map;
    for(auto a:A){
        if(map.count(a)) map.at(a)++;
        else map[a] = 1;
    }
    int tmp = 0;
    int tmp_f;
    for(auto i = map.begin() ; i != map.end(); i++){
        if(i->second > tmp){
            tmp = i->second;
            tmp_f = i->first;
        }
    }
    cout << tmp_f << " " << tmp << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
