#include <bits/stdc++.h>
using namespace std;


void solve(std::vector<std::vector<long long>> A){

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::vector<std::vector<long long>> A(9, std::vector<long long>(9));
    for(int i = 0 ; i < 9 ; i++){
        for(int j = 0 ; j < 9 ; j++){
            scanf("%lld",&A[i][j]);
        }
    }
    solve(std::move(A));
    return 0;
}
