#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> a, std::vector<long long> b){
    vector<pair<int,int>> tp;
    auto ita = a.begin();
    auto itb = b.begin();
    while(ita != a.end() || itb != b.end()){
        tp.push_back(make_pair(*itb,*ita));
        if(ita != a.end()) ++ita;
        if(itb != b.end()) ++itb;
    }
    sort(tp.begin(), tp.end());
    for(auto &elem : tp){
        cout << elem.second << " " << elem.first << endl;
    }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> a(N);
    std::vector<long long> b(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&a[i]);
        scanf("%lld",&b[i]);
    }
    solve(N, std::move(a), std::move(b));
    return 0;
}
